server:
  port: 9192

spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/employee_cards # Вместо employee_cards можете указать свою базу данных.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
